### ISSUE TITLE
A request/help for workspace switching

### ISSUE THREAD

**Issue by alfredjophy** [user18130814200115-2/swayscrips#1]
it would be really cool , if u could have the previous workspace fade out into the next one

**Comment by user18130814200115-2** [comment]
That sounds feasible.
I will see if I can get some time to fulfill your request

**Comment by user18130814200115-2** [comment]
1. mark all windows o the current workspace with fade
2. fade out all widows with fade
3. make all windows in new workspace invisible and mark with fade
4. switch to new workspace
5. fade in all marked windows

**Comment by alfredjophy** [comment]
sounds like it will work
Thanks : )

**Comment by user18130814200115-2** [comment]
https://github.com/user18130814200115-2/swayscrips/tree/main/workspacefade
Is now up, enjoy and feel free to report if you have any issues with it.
