### ISSUE TITLE
some app go through without fadein at startup

### ISSUE THREAD

**Issue by gabuzom** [user18130814200115-2/swayscrips#2]
Hey there!

I love fadein, it's working really great. I really think it's useful and not "just eyecandy", as it makes you spend your time looking at something pretty and dynamic instead of waiting in frustration for an app to launch ;)

Yet over time i found and only one problem with its usage:

* when i launch several apps in my sway config (using exec)
* all of them appear alright but ONE. this one is on screen with 0% opacity. i usually kill it and launch it again..
* strange thing is that it is not always the same one (i launch 3 or 4 apps at startup)

I tried several things: launching exec commands with or without &, moving the fadein section in the config file, etc... but so far haven't found a solution. Do you have an idea?

**Comment by user18130814200115-2** [comment]
I suspect this is a timing issue.
If a window is spawned before the previous window is given a unique id, then the former remains transparent. Alternatively, two windows may receive the same id, though this is improbable.

To test what is happening, do the following:
1. Make sure you have sway title bars turned on, in the top right, they will display the mark.
2. Spawn windows until you encounter the issue.
3. Set the invisible window's opacity to 1. I suggest using `sleep3 && swaymsg opacity 1`, this command is to be run in a terminal and gives you 3 seconds to focus the invisible window.

If the mark (in the top right of the title bar) reads "fade",
then fadein.sh was somehow not called or crashed.
If the mark reads a number, then fadin.sh crashed halfway.
Lastly, if the window has no mark, then we have encountered the timing issue I mentioned before. I think this is most probable.

Lastly, there is a workaround for now.
Add a keybind to your sway config running:
`mark fade; exec fadein.sh`.
You can call the keybind while focusing the broken window to fix it.


PS.
Sorry if there are lots of typos, I wrote this on the train.

**Comment by gabuzom** [comment]
Thanks a lot for a reply @user18130814200115-2 , very much appreciated!!

Simple and elegant solution, and way to know what happens, indeed!

So the title is inded....... (suspense!)....... the actual name of the program (with no mark)!

So it's NOT a bug in fadein, but rather a timing issue? right? how could i test or fix this in my setup script? adding && sleep 0.1 after every of these exec commands, for instance?

Thanks!

**Comment by user18130814200115-2** [comment]
Adding the delay to exec's wont work, it will merely move the timing issue a bit.
The way I see it, there are two possible aproaches:

First, I can write a scrip that always runs and looks for invisible, unmarked windows and makes them fade in. This might conflict with using opacity elsewhere though.

Alternatively, you can have the key bind that fixes the window (from my previous comment) in your standard config.

Finally, there is one thing I can think of that might mitigate the problem, though it is no catch-all solution.
The timing issue will be less prevalent the faster fadein.sh runs. If your `/bin/sh` is liked to bash, I recommend linking it to dash instead (you probably need to install dash first) as it is up to 5 times faster I believe.

**Comment by gabuzom** [comment]
hmm interesting. thanks again!

i won't be using key bindings, as i am using this on a device that have very little keys (3 actually) that are already very much mapped to useful function (sxmo in pmos, on a pinephone!)

then i am already using ash as a /bin/sh, but it's a good idea maybe to try another one. i think i will do that and see what happens.

will keep you informed if anything interesting comes out of it!

**Comment by user18130814200115-2** [comment]
I modified the script a tiny bit.
Getting rid of a redundant call which I thought was harmless, though it may be causing your issue at times.
Give it a try, it may work.
Though there could still give a timing issue, at least your window will be visible.

**Comment by gabuzom** [comment]
nope. same thing :(

**Comment by gabuzom** [comment]
Update: it may only be when two of the startup programms have the same name? tried the two different config:
* launching 3 programms of different name: all fade in nicely
* launching 3 programms including 2 of same name: 1 doesnt fade in
hmm yet it may still be the timing issue, that two exact same terms are likely to be launched in almost the same second...

will try further tests

**Comment by user18130814200115-2** [comment]
I am certain now that I cannot fix this issue, but I did think of a workaround.
**provided that you do not use marks elsewhere** I can write you a script that makes windows without a mark (those affected by this issue) and makes them fade.

Let me know if you are interested

**Comment by gabuzom** [comment]
Hey there!! Sorry it took long to reply i guess i was embarassed by your message as it is somehow **too kind**! :)

I would love a solution, but wouldn't want you to do extra work if this solution would only be useful to me, but if it serves others as well...

On a sidenote i found one new manifestation of the problem: Sometimes when firefox launches and restores a session of multiple windows, one of them appears with 0% opacity too...

Cheers!

**Comment by user18130814200115-2** [comment]
The repo now contains `fadefix.sh`.
This script will run constantly in the background and look for windows every second that are focused but not marked.
If it finds them, it will initiate the fade.
Thus, if you "see" an invisible window, simply focus it and it will fade in shortly.

Add `fadefix.sh` to your PATH and start it in your config file with `exec fadefix.sh`.
Also make sure to use the new version of `fadein.sh` as this keeps the windows marked,
otherwise, you would see an infinite loop of fadefix trying to fade the windows.

If this fixes your issue feel free to close it :)

All the best!

**Comment by gabuzom** [comment]
Thanks a lot! It is very kind of you! Unsure if i'll make this a permanent process in my system, but it may inspire all sorts of fixes! thanks again!
